const { withDangerousMod, withXcodeProject } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

// `ios/` is gitignored and regenerated by `expo prebuild`, so a build phase
// added by hand in Xcode (or via the `xcodeproj` gem one-off fix) doesn't
// survive the next prebuild. This plugin re-adds it every time so local
// Xcode archives always get a fresh CFBundleVersion and stop getting
// rejected by App Store Connect for duplicate build numbers.
const SCRIPT_NAME = "bump-build-number.sh";
const PHASE_NAME = "Bump Build Number";

const SCRIPT_CONTENTS = `#!/bin/bash
set -e

if [ "\${CONFIGURATION}" = "Release" ] && [ "\${ACTION}" = "install" ]; then
  INFOPLIST="\${SRCROOT}/\${PRODUCT_NAME}/Info.plist"
  buildNumber=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "\${INFOPLIST}")
  buildNumber=$((buildNumber + 1))
  /usr/libexec/PlistBuddy -c "Set :CFBundleVersion \${buildNumber}" "\${INFOPLIST}"
  echo "bump-build-number: CFBundleVersion -> \${buildNumber}"
fi
`;

function withBumpBuildNumberScript(config) {
  return withDangerousMod(config, [
    "ios",
    async (config) => {
      const scriptsDir = path.join(config.modRequest.platformProjectRoot, "scripts");
      fs.mkdirSync(scriptsDir, { recursive: true });
      const scriptPath = path.join(scriptsDir, SCRIPT_NAME);
      fs.writeFileSync(scriptPath, SCRIPT_CONTENTS, { mode: 0o755 });
      return config;
    },
  ]);
}

function withBumpBuildNumberPhase(config) {
  return withXcodeProject(config, (config) => {
    const project = config.modResults;
    const target = project.getFirstTarget().uuid;

    const phases = project.hash.project.objects.PBXShellScriptBuildPhase || {};
    const alreadyAdded = Object.values(phases).some((phase) => phase && phase.name === `"${PHASE_NAME}"`);

    if (!alreadyAdded) {
      project.addBuildPhase([], "PBXShellScriptBuildPhase", PHASE_NAME, target, {
        shellPath: "/bin/sh",
        shellScript: `"$SRCROOT/scripts/${SCRIPT_NAME}"`,
      });
    }

    return config;
  });
}

module.exports = function withBumpBuildNumber(config) {
  config = withBumpBuildNumberScript(config);
  config = withBumpBuildNumberPhase(config);
  return config;
};
